version: "2"
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verse
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  node:
    image: "node:latest"
    user: "node"
    depends_on:
      - db
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
    ports:
      - "1337:1337"
    volumes:
      - ./:/home/node/app
    expose:
      - "1337"
    command: "node_modules/.bin/nodemon -e ts --exec npm start"
